
import React, { useState } from 'react';
import { FullDealAnalysis } from '../../types';
import { TrendingUp, Users, AlertTriangle, CheckCircle2, ArrowRight, Shield, Zap, LayoutDashboard, History, Download, FileText, FileSpreadsheet, AlertOctagon, ThumbsUp, XCircle, HelpCircle, Lightbulb, MessageSquare, Target } from 'lucide-react';
import { exportDealReport, downloadScript } from '../../services/exportService';

interface DealDashboardProps {
  analysis: FullDealAnalysis;
}

export const DealDashboard: React.FC<DealDashboardProps> = ({ analysis }) => {
  const [showExportMenu, setShowExportMenu] = useState(false);

  const getWinProbColor = (label: string) => {
    if (label.includes("High")) return 'text-emerald-600 bg-emerald-50 border-emerald-200';
    if (label.includes("Medium")) return 'text-amber-600 bg-amber-50 border-amber-200';
    return 'text-red-600 bg-red-50 border-red-200';
  };

  const handleExport = (format: 'CSV' | 'PDF') => {
    exportDealReport(analysis, format);
    setShowExportMenu(false);
  };

  const handleDownloadScript = () => {
    if (analysis.consolidatedScript) {
      downloadScript(analysis.consolidatedScript, `Deal_Script_${analysis.dealName.replace(/\s+/g, '_')}.txt`);
    }
    setShowExportMenu(false);
  };

  // Helper to normalize values (convert 0.2 to 20, keep 20 as 20)
  const normalize = (val: number | undefined | null) => {
    if (val === undefined || val === null) return 0;
    return (val > 0 && val <= 1) ? Math.round(val * 100) : Math.round(val);
  };

  const winProbScore = normalize(analysis.winProbability.score);

  return (
    <div className="animate-fade-in space-y-6 pb-20">
      {/* Header */}
      <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
           <div className="flex items-center gap-2 mb-1">
             <span className="text-xs font-bold bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded uppercase">Deal Analysis</span>
             <span className="text-xs text-slate-400">Generated by Gemini 3.0 Pro</span>
           </div>
           <h1 className="text-2xl font-extrabold text-slate-800">{analysis.dealName}</h1>
           <p className="text-slate-500 text-sm max-w-2xl mt-1">{analysis.executiveSummary}</p>
        </div>
        
        <div className="flex items-center gap-4">
            <div className={`px-6 py-4 rounded-xl border flex flex-col items-center min-w-[200px] ${getWinProbColor(analysis.winProbability.label)}`}>
               <span className="text-xs font-bold uppercase tracking-wider opacity-80">Win Probability</span>
               <span className="text-3xl font-extrabold">{winProbScore}%</span>
               <span className="text-xs font-bold mt-1">{analysis.winProbability.label}</span>
            </div>

            {/* Export Button */}
            <div className="relative">
                <button 
                  onClick={() => setShowExportMenu(!showExportMenu)}
                  className="p-3 bg-white border border-slate-200 hover:bg-slate-50 text-slate-600 rounded-xl shadow-sm transition-colors"
                >
                    <Download className="w-6 h-6" />
                </button>
                {showExportMenu && (
                  <div className="absolute right-0 top-full mt-2 w-56 bg-white border border-slate-200 rounded-xl shadow-xl z-50 overflow-hidden animate-fade-in">
                    <button 
                      onClick={() => handleExport('PDF')}
                      className="w-full text-left px-4 py-3 text-sm text-slate-700 hover:bg-slate-50 flex items-center gap-2 border-b border-slate-50"
                    >
                      <FileText className="w-4 h-4 text-red-600" /> PDF Report
                    </button>
                    <button 
                      onClick={() => handleExport('CSV')}
                      className="w-full text-left px-4 py-3 text-sm text-slate-700 hover:bg-slate-50 flex items-center gap-2 border-b border-slate-50"
                    >
                      <FileSpreadsheet className="w-4 h-4 text-green-600" /> Excel / CSV
                    </button>
                    <button 
                      onClick={handleDownloadScript}
                      disabled={!analysis.consolidatedScript}
                      className="w-full text-left px-4 py-3 text-sm text-slate-700 hover:bg-slate-50 flex items-center gap-2 disabled:opacity-50"
                    >
                      <MessageSquare className="w-4 h-4 text-blue-600" /> Download Deal Script
                    </button>
                  </div>
                )}
            </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* LEFT COLUMN: Timeline & Journey & Insights */}
        <div className="lg:col-span-2 space-y-6">
           
           {/* New: Deal Highlights (Missed Opps / Key Moments) */}
           <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-emerald-50 rounded-xl border border-emerald-100 p-5">
                 <h3 className="font-bold text-emerald-900 mb-3 flex items-center gap-2">
                    <ThumbsUp className="w-4 h-4" /> Winning Moments
                 </h3>
                 <ul className="space-y-2">
                    {(analysis.keyMoments || []).map((m, i) => (
                        <li key={i} className="text-sm text-emerald-800 flex gap-2 items-start">
                            <span className="font-bold">•</span> {m}
                        </li>
                    ))}
                    {(!analysis.keyMoments || analysis.keyMoments.length === 0) && <li className="text-sm text-emerald-700 italic">No key moments identified.</li>}
                 </ul>
              </div>
              <div className="bg-amber-50 rounded-xl border border-amber-100 p-5">
                 <h3 className="font-bold text-amber-900 mb-3 flex items-center gap-2">
                    <AlertTriangle className="w-4 h-4" /> Missed Opportunities
                 </h3>
                 <ul className="space-y-2">
                    {(analysis.missedOpportunities || []).map((m, i) => (
                        <li key={i} className="text-sm text-amber-900 flex gap-2 items-start">
                             <span className="font-bold">•</span> {m}
                        </li>
                    ))}
                    {(!analysis.missedOpportunities || analysis.missedOpportunities.length === 0) && <li className="text-sm text-amber-800 italic">No missed opportunities identified.</li>}
                 </ul>
              </div>
           </div>

           {/* New: Deal Coaching Insights */}
           {analysis.coachingInsights && (
             <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
                  <Lightbulb className="w-5 h-5 text-yellow-500" /> Deal Coaching Insights
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                   <div>
                      <h4 className="text-xs font-bold text-slate-400 uppercase mb-2">Improvement Areas</h4>
                      <ul className="space-y-2">
                        {(analysis.coachingInsights.improvementAreas || []).map((item, i) => (
                          <li key={i} className="text-sm text-slate-600 flex gap-2 items-start">
                             <span className="text-amber-500 font-bold">•</span> {item}
                          </li>
                        ))}
                      </ul>
                   </div>
                   <div>
                      <h4 className="text-xs font-bold text-slate-400 uppercase mb-2">Key Takeaways</h4>
                      <ul className="space-y-2">
                        {(analysis.coachingInsights.keyTakeaways || []).map((item, i) => (
                          <li key={i} className="text-sm text-slate-600 flex gap-2 items-start">
                             <span className="text-indigo-500 font-bold">•</span> {item}
                          </li>
                        ))}
                      </ul>
                   </div>
                </div>
             </div>
           )}

           {/* Journey Map */}
           <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
              <h3 className="font-bold text-slate-800 mb-6 flex items-center gap-2">
                <History className="w-5 h-5 text-blue-500" /> Deal Journey Timeline
              </h3>
              <div className="relative border-l-2 border-slate-200 ml-3 space-y-8 pl-8 py-2">
                 {(analysis.journeyTimeline || []).map((point, idx) => (
                    <div key={idx} className="relative">
                       <div className={`absolute -left-[41px] top-1 w-6 h-6 rounded-full border-4 border-white shadow-sm flex items-center justify-center ${
                         point.sentiment === 'Positive' ? 'bg-emerald-500' : point.sentiment === 'Negative' ? 'bg-red-500' : 'bg-slate-400'
                       }`}></div>
                       
                       <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-1">
                          <div>
                            <span className="text-xs font-bold text-slate-400 uppercase">{point.date}</span>
                            <h4 className="font-bold text-slate-800 text-lg">{point.stage}</h4>
                          </div>
                          <span className={`text-[10px] font-bold px-2 py-0.5 rounded self-start ${
                            point.sentiment === 'Positive' ? 'bg-emerald-100 text-emerald-700' : 
                            point.sentiment === 'Negative' ? 'bg-red-100 text-red-700' : 'bg-slate-100 text-slate-600'
                          }`}>
                            {point.sentiment} Sentiment
                          </span>
                       </div>
                       
                       <p className="text-slate-600 text-sm mt-2">{point.summary}</p>
                       <div className="mt-2 bg-slate-50 border border-slate-100 p-2 rounded-lg">
                          <p className="text-xs text-slate-500 italic">"{point.keySignal}"</p>
                       </div>
                    </div>
                 ))}
              </div>
           </div>

           {/* New: Consolidated Deal Script */}
           {analysis.consolidatedScript && (
             <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="font-bold text-slate-800 flex items-center gap-2">
                    <MessageSquare className="w-5 h-5 text-blue-500" /> Consolidated Deal Script
                  </h3>
                  <button 
                    onClick={handleDownloadScript}
                    className="text-xs font-bold text-blue-600 hover:text-blue-700 flex items-center gap-1"
                  >
                    <Download className="w-3 h-3" /> Download .txt
                  </button>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl border border-slate-100 max-h-[400px] overflow-y-auto custom-scrollbar">
                   <pre className="text-xs text-slate-600 whitespace-pre-wrap font-sans leading-relaxed">
                      {analysis.consolidatedScript}
                   </pre>
                </div>
             </div>
           )}

           {/* Stakeholders */}
           <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
              <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
                <Users className="w-5 h-5 text-indigo-500" /> Stakeholder Map
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                 {(analysis.stakeholders || []).map((person, idx) => (
                    <div key={idx} className="flex items-center p-3 border border-slate-100 rounded-lg bg-slate-50">
                       <div className={`w-10 h-10 rounded-full flex items-center justify-center font-bold text-white mr-3 ${
                         person.role === 'Decision Maker' ? 'bg-purple-600' : 'bg-slate-400'
                       }`}>
                          {person.nameOrReference.charAt(0)}
                       </div>
                       <div>
                          <p className="font-bold text-slate-800 text-sm">{person.nameOrReference}</p>
                          <p className="text-xs text-slate-500">{person.role}</p>
                       </div>
                       <div className={`ml-auto w-2 h-2 rounded-full ${
                          person.sentiment === 'Positive' ? 'bg-emerald-500' : person.sentiment === 'Negative' ? 'bg-red-500' : 'bg-slate-300'
                       }`} title={person.sentiment}></div>
                    </div>
                 ))}
              </div>
           </div>
        </div>

        {/* RIGHT COLUMN: Action, Risks, QA */}
        <div className="space-y-6">
           
           {/* Action Plan */}
           <div className="bg-indigo-900 text-white p-6 rounded-xl shadow-lg border border-indigo-800">
              <h3 className="font-bold text-lg mb-4 flex items-center gap-2">
                <Zap className="w-5 h-5 text-yellow-400" /> Strategic Next Steps
              </h3>
              <ul className="space-y-4">
                 {(analysis.actionPlan?.nextSteps || []).map((step, idx) => (
                    <li key={idx} className="flex gap-3 items-start">
                       <div className="mt-1 bg-indigo-700 p-1 rounded">
                         <ArrowRight className="w-3 h-3 text-white" />
                       </div>
                       <p className="text-sm font-medium text-indigo-100 leading-snug">{step}</p>
                    </li>
                 ))}
              </ul>
           </div>

           {/* New: Key Questions */}
           {analysis.keyQuestions && analysis.keyQuestions.length > 0 && (
             <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
                  <HelpCircle className="w-5 h-5 text-purple-500" /> Strategic Questions
                </h3>
                <ul className="space-y-3">
                   {analysis.keyQuestions.map((q, idx) => (
                     <li key={idx} className="text-sm text-slate-600 flex gap-2 items-start bg-purple-50 p-2 rounded border border-purple-100">
                        <span className="text-purple-500 font-bold">Q:</span> {q}
                     </li>
                   ))}
                </ul>
             </div>
           )}

           {/* New: Closing Strategies */}
           {analysis.closingSuggestions && analysis.closingSuggestions.length > 0 && (
             <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
                  <Target className="w-5 h-5 text-rose-500" /> Closing Strategies
                </h3>
                <div className="space-y-4">
                   {analysis.closingSuggestions.map((s, idx) => (
                     <div key={idx} className="bg-rose-50 p-3 rounded-lg border border-rose-100">
                        <p className="text-sm font-bold text-rose-900 mb-1">{s.strategy}</p>
                        <p className="text-xs text-slate-600">{s.rationale}</p>
                     </div>
                   ))}
                </div>
             </div>
           )}
           
           {/* Deal Health QA (New) */}
           <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
              <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
                 <Shield className="w-5 h-5 text-blue-500" /> Deal Health Check
              </h3>
              <div className="space-y-3">
                 {(analysis.dealHealthChecks || []).map((check, idx) => (
                    <div key={idx} className="flex items-start gap-3 p-2 border-b border-slate-50 last:border-0">
                       {check.status === 'Pass' ? (
                          <CheckCircle2 className="w-4 h-4 text-emerald-500 mt-0.5 flex-shrink-0" />
                       ) : check.status === 'Fail' ? (
                          <XCircle className="w-4 h-4 text-red-500 mt-0.5 flex-shrink-0" />
                       ) : (
                          <AlertOctagon className="w-4 h-4 text-amber-500 mt-0.5 flex-shrink-0" />
                       )}
                       <div>
                          <p className={`text-sm font-bold ${check.status === 'Pass' ? 'text-slate-700' : check.status === 'Fail' ? 'text-red-700' : 'text-amber-700'}`}>
                             {check.check}
                          </p>
                          <p className="text-xs text-slate-500">{check.details}</p>
                       </div>
                    </div>
                 ))}
                 {(!analysis.dealHealthChecks || analysis.dealHealthChecks.length === 0) && (
                     <p className="text-sm text-slate-400 italic">No health checks available.</p>
                 )}
              </div>
           </div>

           {/* Risks */}
           <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
              <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
                <AlertTriangle className="w-5 h-5 text-orange-500" /> Risks to Mitigate
              </h3>
              <ul className="space-y-3">
                 {(analysis.actionPlan?.risksToMitigate || []).map((risk, idx) => (
                    <li key={idx} className="text-sm text-slate-600 flex gap-2 items-start bg-orange-50 p-2 rounded border border-orange-100">
                       <span className="text-orange-500 font-bold">•</span> {risk}
                    </li>
                 ))}
              </ul>
           </div>

           {/* Objections Tracker */}
           <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
              <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
                <Shield className="w-5 h-5 text-red-500" /> Objection Tracker
              </h3>
              <div className="space-y-3 max-h-[300px] overflow-y-auto custom-scrollbar">
                 {(analysis.allObjections || []).map((obj, idx) => (
                    <div key={idx} className={`p-3 rounded-lg border text-sm ${obj.status === 'Resolved' ? 'bg-slate-50 border-slate-200 opacity-70' : 'bg-red-50 border-red-100'}`}>
                       <div className="flex justify-between items-start mb-1">
                          <span className={`font-bold text-xs px-1.5 py-0.5 rounded ${obj.status === 'Resolved' ? 'bg-slate-200 text-slate-600' : 'bg-red-200 text-red-700'}`}>
                            {obj.status}
                          </span>
                       </div>
                       <p className="font-bold text-slate-700 mb-1">{obj.objection}</p>
                       <p className="text-xs text-slate-500">{obj.strategy}</p>
                    </div>
                 ))}
              </div>
           </div>

        </div>
      </div>
    </div>
  );
};
